[[plugins]]
package = "@netlify/plugin-sitemap"

# Uncomment the below when due to go live to public
# Some other things will need to be set up within Sentry.
# If you've not done this, then ask for help.
# [[plugins]]
# package = "@sentry/netlify-build-plugin"

# [plugins.inputs]
#   sentryOrg = "wmca-digital"
#   sentryProject = "wmn-disrapp-name"